language: java

jdk: 
  - openjdk8

cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean compile
  - mvn test
  - mvn package
after_success: mvn clean test jacoco:report coveralls:report